// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: brands.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getBrandByID = `-- name: GetBrandByID :one
SELECT id, name, slug, logo_url, description, created_at FROM brands WHERE id = $1
`

func (q *Queries) GetBrandByID(ctx context.Context, id uuid.UUID) (Brand, error) {
	row := q.db.QueryRow(ctx, getBrandByID, id)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LogoUrl,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getBrandBySlug = `-- name: GetBrandBySlug :one
SELECT id, name, slug, logo_url, description, created_at FROM brands WHERE slug = $1
`

func (q *Queries) GetBrandBySlug(ctx context.Context, slug string) (Brand, error) {
	row := q.db.QueryRow(ctx, getBrandBySlug, slug)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LogoUrl,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listBrands = `-- name: ListBrands :many
SELECT id, name, slug, logo_url, description, created_at FROM brands ORDER BY name
`

func (q *Queries) ListBrands(ctx context.Context) ([]Brand, error) {
	rows, err := q.db.Query(ctx, listBrands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Brand
	for rows.Next() {
		var i Brand
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.LogoUrl,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchBrands = `-- name: SearchBrands :many
SELECT id, name, slug, logo_url, description, created_at FROM brands
WHERE name ILIKE '%' || $1 || '%'
   OR slug ILIKE '%' || $1 || '%'
ORDER BY similarity(name, $1) DESC
LIMIT 8
`

func (q *Queries) SearchBrands(ctx context.Context, query *string) ([]Brand, error) {
	rows, err := q.db.Query(ctx, searchBrands, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Brand
	for rows.Next() {
		var i Brand
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.LogoUrl,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
