// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: favorites.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addFavorite = `-- name: AddFavorite :exec
INSERT INTO favorites (user_id, pen_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddFavoriteParams struct {
	UserID uuid.UUID `json:"user_id"`
	PenID  uuid.UUID `json:"pen_id"`
}

func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) error {
	_, err := q.db.Exec(ctx, addFavorite, arg.UserID, arg.PenID)
	return err
}

const isFavorite = `-- name: IsFavorite :one
SELECT EXISTS(
    SELECT 1 FROM favorites WHERE user_id = $1 AND pen_id = $2
)::bool AS is_favorite
`

type IsFavoriteParams struct {
	UserID uuid.UUID `json:"user_id"`
	PenID  uuid.UUID `json:"pen_id"`
}

func (q *Queries) IsFavorite(ctx context.Context, arg IsFavoriteParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFavorite, arg.UserID, arg.PenID)
	var is_favorite bool
	err := row.Scan(&is_favorite)
	return is_favorite, err
}

const listFavoritesByUser = `-- name: ListFavoritesByUser :many
SELECT
    p.id, p.brand_id, p.name, p.slug, p.description, p.type, p.ink_type, p.tip_size, p.price, p.weight, p.length, p.grip_material, p.body_material, p.color, p.smoothness_score, p.comfort_score, p.durability_score, p.precision_score, p.design_score, p.grip_score, p.ink_quality, p.image_url, p.why_good, p.suitable_for, p.not_suitable_for, p.created_at, p.updated_at,
    b.name AS brand_name,
    b.slug AS brand_slug,
    COALESCE(AVG(r.rating), 0)::float AS avg_rating,
    COUNT(r.id)::int AS review_count
FROM favorites f
JOIN pens p ON p.id = f.pen_id
JOIN brands b ON b.id = p.brand_id
LEFT JOIN reviews r ON r.pen_id = p.id
WHERE f.user_id = $1
GROUP BY p.id, b.name, b.slug, f.created_at
ORDER BY f.created_at DESC
`

type ListFavoritesByUserRow struct {
	ID              uuid.UUID          `json:"id"`
	BrandID         uuid.UUID          `json:"brand_id"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	Description     string             `json:"description"`
	Type            string             `json:"type"`
	InkType         string             `json:"ink_type"`
	TipSize         string             `json:"tip_size"`
	Price           float64            `json:"price"`
	Weight          float64            `json:"weight"`
	Length          pgtype.Numeric     `json:"length"`
	GripMaterial    *string            `json:"grip_material"`
	BodyMaterial    *string            `json:"body_material"`
	Color           *string            `json:"color"`
	SmoothnessScore float64            `json:"smoothness_score"`
	ComfortScore    float64            `json:"comfort_score"`
	DurabilityScore float64            `json:"durability_score"`
	PrecisionScore  float64            `json:"precision_score"`
	DesignScore     float64            `json:"design_score"`
	GripScore       float64            `json:"grip_score"`
	InkQuality      float64            `json:"ink_quality"`
	ImageUrl        *string            `json:"image_url"`
	WhyGood         *string            `json:"why_good"`
	SuitableFor     *string            `json:"suitable_for"`
	NotSuitableFor  *string            `json:"not_suitable_for"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	BrandName       string             `json:"brand_name"`
	BrandSlug       string             `json:"brand_slug"`
	AvgRating       float64            `json:"avg_rating"`
	ReviewCount     int32              `json:"review_count"`
}

func (q *Queries) ListFavoritesByUser(ctx context.Context, userID uuid.UUID) ([]ListFavoritesByUserRow, error) {
	rows, err := q.db.Query(ctx, listFavoritesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFavoritesByUserRow
	for rows.Next() {
		var i ListFavoritesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.BrandID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Type,
			&i.InkType,
			&i.TipSize,
			&i.Price,
			&i.Weight,
			&i.Length,
			&i.GripMaterial,
			&i.BodyMaterial,
			&i.Color,
			&i.SmoothnessScore,
			&i.ComfortScore,
			&i.DurabilityScore,
			&i.PrecisionScore,
			&i.DesignScore,
			&i.GripScore,
			&i.InkQuality,
			&i.ImageUrl,
			&i.WhyGood,
			&i.SuitableFor,
			&i.NotSuitableFor,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BrandName,
			&i.BrandSlug,
			&i.AvgRating,
			&i.ReviewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavorite = `-- name: RemoveFavorite :exec
DELETE FROM favorites WHERE user_id = $1 AND pen_id = $2
`

type RemoveFavoriteParams struct {
	UserID uuid.UUID `json:"user_id"`
	PenID  uuid.UUID `json:"pen_id"`
}

func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error {
	_, err := q.db.Exec(ctx, removeFavorite, arg.UserID, arg.PenID)
	return err
}
