// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Brand struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	LogoUrl     *string            `json:"logo_url"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Category struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Slug string    `json:"slug"`
}

type Comparison struct {
	ID        uuid.UUID          `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ComparisonPen struct {
	ComparisonID uuid.UUID `json:"comparison_id"`
	PenID        uuid.UUID `json:"pen_id"`
}

type Favorite struct {
	UserID    uuid.UUID          `json:"user_id"`
	PenID     uuid.UUID          `json:"pen_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Pen struct {
	ID              uuid.UUID          `json:"id"`
	BrandID         uuid.UUID          `json:"brand_id"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	Description     string             `json:"description"`
	Type            string             `json:"type"`
	InkType         string             `json:"ink_type"`
	TipSize         string             `json:"tip_size"`
	Price           float64            `json:"price"`
	Weight          float64            `json:"weight"`
	Length          pgtype.Numeric     `json:"length"`
	GripMaterial    *string            `json:"grip_material"`
	BodyMaterial    *string            `json:"body_material"`
	Color           *string            `json:"color"`
	SmoothnessScore float64            `json:"smoothness_score"`
	ComfortScore    float64            `json:"comfort_score"`
	DurabilityScore float64            `json:"durability_score"`
	PrecisionScore  float64            `json:"precision_score"`
	DesignScore     float64            `json:"design_score"`
	GripScore       float64            `json:"grip_score"`
	InkQuality      float64            `json:"ink_quality"`
	ImageUrl        *string            `json:"image_url"`
	WhyGood         *string            `json:"why_good"`
	SuitableFor     *string            `json:"suitable_for"`
	NotSuitableFor  *string            `json:"not_suitable_for"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type PenCategory struct {
	PenID      uuid.UUID `json:"pen_id"`
	CategoryID uuid.UUID `json:"category_id"`
}

type PenFeature struct {
	ID    uuid.UUID `json:"id"`
	Key   string    `json:"key"`
	Label string    `json:"label"`
}

type PenFeatureValue struct {
	PenID     uuid.UUID `json:"pen_id"`
	FeatureID uuid.UUID `json:"feature_id"`
	Value     string    `json:"value"`
}

type PenTag struct {
	PenID uuid.UUID `json:"pen_id"`
	TagID uuid.UUID `json:"tag_id"`
}

type RefreshToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Review struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	PenID     uuid.UUID          `json:"pen_id"`
	Rating    int16              `json:"rating"`
	Title     *string            `json:"title"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Tag struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Slug string    `json:"slug"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
