// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pens.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPens = `-- name: CountPens :one
SELECT COUNT(*)::int
FROM pens p
JOIN brands b ON b.id = p.brand_id
WHERE
    ($1::text IS NULL OR b.slug = $1)
    AND ($2::text IS NULL OR p.type = $2)
    AND ($3::text IS NULL OR p.ink_type = $3)
    AND ($4::text IS NULL OR p.tip_size = $4)
    AND ($5::text IS NULL OR p.color ILIKE $5)
    AND ($6::numeric IS NULL OR p.price >= $6)
    AND ($7::numeric IS NULL OR p.price <= $7)
    AND ($8::numeric IS NULL OR p.weight >= $8)
    AND ($9::numeric IS NULL OR p.weight <= $9)
    AND ($10::float IS NULL OR (
        SELECT COALESCE(AVG(r2.rating), 0) FROM reviews r2 WHERE r2.pen_id = p.id
    ) >= $10)
    AND (
        $11::text IS NULL OR EXISTS (
            SELECT 1 FROM pen_tags pt
            JOIN tags t ON t.id = pt.tag_id
            WHERE pt.pen_id = p.id AND t.slug = $11
        )
    )
`

type CountPensParams struct {
	BrandSlug *string        `json:"brand_slug"`
	Type      *string        `json:"type"`
	InkType   *string        `json:"ink_type"`
	TipSize   *string        `json:"tip_size"`
	Color     *string        `json:"color"`
	MinPrice  pgtype.Numeric `json:"min_price"`
	MaxPrice  pgtype.Numeric `json:"max_price"`
	MinWeight pgtype.Numeric `json:"min_weight"`
	MaxWeight pgtype.Numeric `json:"max_weight"`
	MinRating *float64       `json:"min_rating"`
	Purpose   *string        `json:"purpose"`
}

func (q *Queries) CountPens(ctx context.Context, arg CountPensParams) (int32, error) {
	row := q.db.QueryRow(ctx, countPens,
		arg.BrandSlug,
		arg.Type,
		arg.InkType,
		arg.TipSize,
		arg.Color,
		arg.MinPrice,
		arg.MaxPrice,
		arg.MinWeight,
		arg.MaxWeight,
		arg.MinRating,
		arg.Purpose,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countPensTotal = `-- name: CountPensTotal :one
SELECT COUNT(*)::int FROM pens
`

func (q *Queries) CountPensTotal(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countPensTotal)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getPenByID = `-- name: GetPenByID :one
SELECT
    p.id, p.brand_id, p.name, p.slug, p.description, p.type, p.ink_type, p.tip_size, p.price, p.weight, p.length, p.grip_material, p.body_material, p.color, p.smoothness_score, p.comfort_score, p.durability_score, p.precision_score, p.design_score, p.grip_score, p.ink_quality, p.image_url, p.why_good, p.suitable_for, p.not_suitable_for, p.created_at, p.updated_at,
    b.name AS brand_name,
    b.slug AS brand_slug,
    COALESCE(AVG(r.rating), 0)::float AS avg_rating,
    COUNT(r.id)::int AS review_count
FROM pens p
JOIN brands b ON b.id = p.brand_id
LEFT JOIN reviews r ON r.pen_id = p.id
WHERE p.id = $1
GROUP BY p.id, b.name, b.slug
`

type GetPenByIDRow struct {
	ID              uuid.UUID          `json:"id"`
	BrandID         uuid.UUID          `json:"brand_id"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	Description     string             `json:"description"`
	Type            string             `json:"type"`
	InkType         string             `json:"ink_type"`
	TipSize         string             `json:"tip_size"`
	Price           float64            `json:"price"`
	Weight          float64            `json:"weight"`
	Length          pgtype.Numeric     `json:"length"`
	GripMaterial    *string            `json:"grip_material"`
	BodyMaterial    *string            `json:"body_material"`
	Color           *string            `json:"color"`
	SmoothnessScore float64            `json:"smoothness_score"`
	ComfortScore    float64            `json:"comfort_score"`
	DurabilityScore float64            `json:"durability_score"`
	PrecisionScore  float64            `json:"precision_score"`
	DesignScore     float64            `json:"design_score"`
	GripScore       float64            `json:"grip_score"`
	InkQuality      float64            `json:"ink_quality"`
	ImageUrl        *string            `json:"image_url"`
	WhyGood         *string            `json:"why_good"`
	SuitableFor     *string            `json:"suitable_for"`
	NotSuitableFor  *string            `json:"not_suitable_for"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	BrandName       string             `json:"brand_name"`
	BrandSlug       string             `json:"brand_slug"`
	AvgRating       float64            `json:"avg_rating"`
	ReviewCount     int32              `json:"review_count"`
}

func (q *Queries) GetPenByID(ctx context.Context, id uuid.UUID) (GetPenByIDRow, error) {
	row := q.db.QueryRow(ctx, getPenByID, id)
	var i GetPenByIDRow
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Type,
		&i.InkType,
		&i.TipSize,
		&i.Price,
		&i.Weight,
		&i.Length,
		&i.GripMaterial,
		&i.BodyMaterial,
		&i.Color,
		&i.SmoothnessScore,
		&i.ComfortScore,
		&i.DurabilityScore,
		&i.PrecisionScore,
		&i.DesignScore,
		&i.GripScore,
		&i.InkQuality,
		&i.ImageUrl,
		&i.WhyGood,
		&i.SuitableFor,
		&i.NotSuitableFor,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BrandName,
		&i.BrandSlug,
		&i.AvgRating,
		&i.ReviewCount,
	)
	return i, err
}

const getPenBySlug = `-- name: GetPenBySlug :one
SELECT
    p.id, p.brand_id, p.name, p.slug, p.description, p.type, p.ink_type, p.tip_size, p.price, p.weight, p.length, p.grip_material, p.body_material, p.color, p.smoothness_score, p.comfort_score, p.durability_score, p.precision_score, p.design_score, p.grip_score, p.ink_quality, p.image_url, p.why_good, p.suitable_for, p.not_suitable_for, p.created_at, p.updated_at,
    b.name AS brand_name,
    b.slug AS brand_slug,
    COALESCE(AVG(r.rating), 0)::float AS avg_rating,
    COUNT(r.id)::int AS review_count
FROM pens p
JOIN brands b ON b.id = p.brand_id
LEFT JOIN reviews r ON r.pen_id = p.id
WHERE p.slug = $1
GROUP BY p.id, b.name, b.slug
`

type GetPenBySlugRow struct {
	ID              uuid.UUID          `json:"id"`
	BrandID         uuid.UUID          `json:"brand_id"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	Description     string             `json:"description"`
	Type            string             `json:"type"`
	InkType         string             `json:"ink_type"`
	TipSize         string             `json:"tip_size"`
	Price           float64            `json:"price"`
	Weight          float64            `json:"weight"`
	Length          pgtype.Numeric     `json:"length"`
	GripMaterial    *string            `json:"grip_material"`
	BodyMaterial    *string            `json:"body_material"`
	Color           *string            `json:"color"`
	SmoothnessScore float64            `json:"smoothness_score"`
	ComfortScore    float64            `json:"comfort_score"`
	DurabilityScore float64            `json:"durability_score"`
	PrecisionScore  float64            `json:"precision_score"`
	DesignScore     float64            `json:"design_score"`
	GripScore       float64            `json:"grip_score"`
	InkQuality      float64            `json:"ink_quality"`
	ImageUrl        *string            `json:"image_url"`
	WhyGood         *string            `json:"why_good"`
	SuitableFor     *string            `json:"suitable_for"`
	NotSuitableFor  *string            `json:"not_suitable_for"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	BrandName       string             `json:"brand_name"`
	BrandSlug       string             `json:"brand_slug"`
	AvgRating       float64            `json:"avg_rating"`
	ReviewCount     int32              `json:"review_count"`
}

func (q *Queries) GetPenBySlug(ctx context.Context, slug string) (GetPenBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPenBySlug, slug)
	var i GetPenBySlugRow
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Type,
		&i.InkType,
		&i.TipSize,
		&i.Price,
		&i.Weight,
		&i.Length,
		&i.GripMaterial,
		&i.BodyMaterial,
		&i.Color,
		&i.SmoothnessScore,
		&i.ComfortScore,
		&i.DurabilityScore,
		&i.PrecisionScore,
		&i.DesignScore,
		&i.GripScore,
		&i.InkQuality,
		&i.ImageUrl,
		&i.WhyGood,
		&i.SuitableFor,
		&i.NotSuitableFor,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BrandName,
		&i.BrandSlug,
		&i.AvgRating,
		&i.ReviewCount,
	)
	return i, err
}

const getPenFeatureValues = `-- name: GetPenFeatureValues :many
SELECT f.key, f.label, v.value
FROM pen_feature_values v
JOIN pen_features f ON f.id = v.feature_id
WHERE v.pen_id = $1
ORDER BY f.label
`

type GetPenFeatureValuesRow struct {
	Key   string `json:"key"`
	Label string `json:"label"`
	Value string `json:"value"`
}

func (q *Queries) GetPenFeatureValues(ctx context.Context, penID uuid.UUID) ([]GetPenFeatureValuesRow, error) {
	rows, err := q.db.Query(ctx, getPenFeatureValues, penID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPenFeatureValuesRow
	for rows.Next() {
		var i GetPenFeatureValuesRow
		if err := rows.Scan(&i.Key, &i.Label, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPenTags = `-- name: GetPenTags :many
SELECT t.id, t.name, t.slug
FROM tags t
JOIN pen_tags pt ON pt.tag_id = t.id
WHERE pt.pen_id = $1
ORDER BY t.name
`

func (q *Queries) GetPenTags(ctx context.Context, penID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getPenTags, penID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPensForRecommendation = `-- name: ListAllPensForRecommendation :many
SELECT
    p.id, p.brand_id, p.name, p.slug, p.description, p.type, p.ink_type, p.tip_size, p.price, p.weight, p.length, p.grip_material, p.body_material, p.color, p.smoothness_score, p.comfort_score, p.durability_score, p.precision_score, p.design_score, p.grip_score, p.ink_quality, p.image_url, p.why_good, p.suitable_for, p.not_suitable_for, p.created_at, p.updated_at,
    b.name AS brand_name,
    b.slug AS brand_slug,
    COALESCE(AVG(r.rating), 0)::float AS avg_rating,
    COUNT(r.id)::int AS review_count
FROM pens p
JOIN brands b ON b.id = p.brand_id
LEFT JOIN reviews r ON r.pen_id = p.id
GROUP BY p.id, b.name, b.slug
`

type ListAllPensForRecommendationRow struct {
	ID              uuid.UUID          `json:"id"`
	BrandID         uuid.UUID          `json:"brand_id"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	Description     string             `json:"description"`
	Type            string             `json:"type"`
	InkType         string             `json:"ink_type"`
	TipSize         string             `json:"tip_size"`
	Price           float64            `json:"price"`
	Weight          float64            `json:"weight"`
	Length          pgtype.Numeric     `json:"length"`
	GripMaterial    *string            `json:"grip_material"`
	BodyMaterial    *string            `json:"body_material"`
	Color           *string            `json:"color"`
	SmoothnessScore float64            `json:"smoothness_score"`
	ComfortScore    float64            `json:"comfort_score"`
	DurabilityScore float64            `json:"durability_score"`
	PrecisionScore  float64            `json:"precision_score"`
	DesignScore     float64            `json:"design_score"`
	GripScore       float64            `json:"grip_score"`
	InkQuality      float64            `json:"ink_quality"`
	ImageUrl        *string            `json:"image_url"`
	WhyGood         *string            `json:"why_good"`
	SuitableFor     *string            `json:"suitable_for"`
	NotSuitableFor  *string            `json:"not_suitable_for"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	BrandName       string             `json:"brand_name"`
	BrandSlug       string             `json:"brand_slug"`
	AvgRating       float64            `json:"avg_rating"`
	ReviewCount     int32              `json:"review_count"`
}

func (q *Queries) ListAllPensForRecommendation(ctx context.Context) ([]ListAllPensForRecommendationRow, error) {
	rows, err := q.db.Query(ctx, listAllPensForRecommendation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllPensForRecommendationRow
	for rows.Next() {
		var i ListAllPensForRecommendationRow
		if err := rows.Scan(
			&i.ID,
			&i.BrandID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Type,
			&i.InkType,
			&i.TipSize,
			&i.Price,
			&i.Weight,
			&i.Length,
			&i.GripMaterial,
			&i.BodyMaterial,
			&i.Color,
			&i.SmoothnessScore,
			&i.ComfortScore,
			&i.DurabilityScore,
			&i.PrecisionScore,
			&i.DesignScore,
			&i.GripScore,
			&i.InkQuality,
			&i.ImageUrl,
			&i.WhyGood,
			&i.SuitableFor,
			&i.NotSuitableFor,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BrandName,
			&i.BrandSlug,
			&i.AvgRating,
			&i.ReviewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPens = `-- name: ListPens :many
SELECT
    p.id, p.brand_id, p.name, p.slug, p.description, p.type, p.ink_type, p.tip_size, p.price, p.weight, p.length, p.grip_material, p.body_material, p.color, p.smoothness_score, p.comfort_score, p.durability_score, p.precision_score, p.design_score, p.grip_score, p.ink_quality, p.image_url, p.why_good, p.suitable_for, p.not_suitable_for, p.created_at, p.updated_at,
    b.name AS brand_name,
    b.slug AS brand_slug,
    COALESCE(AVG(r.rating), 0)::float AS avg_rating,
    COUNT(r.id)::int AS review_count
FROM pens p
JOIN brands b ON b.id = p.brand_id
LEFT JOIN reviews r ON r.pen_id = p.id
WHERE
    ($1::text IS NULL OR b.slug = $1)
    AND ($2::text IS NULL OR p.type = $2)
    AND ($3::text IS NULL OR p.ink_type = $3)
    AND ($4::text IS NULL OR p.tip_size = $4)
    AND ($5::text IS NULL OR p.color ILIKE $5)
    AND ($6::numeric IS NULL OR p.price >= $6)
    AND ($7::numeric IS NULL OR p.price <= $7)
    AND ($8::numeric IS NULL OR p.weight >= $8)
    AND ($9::numeric IS NULL OR p.weight <= $9)
    AND ($10::float IS NULL OR (
        SELECT COALESCE(AVG(r2.rating), 0) FROM reviews r2 WHERE r2.pen_id = p.id
    ) >= $10)
    AND (
        $11::text IS NULL OR EXISTS (
            SELECT 1 FROM pen_tags pt
            JOIN tags t ON t.id = pt.tag_id
            WHERE pt.pen_id = p.id AND t.slug = $11
        )
    )
GROUP BY p.id, b.name, b.slug
ORDER BY avg_rating DESC, p.name ASC
LIMIT $13 OFFSET $12
`

type ListPensParams struct {
	BrandSlug   *string        `json:"brand_slug"`
	Type        *string        `json:"type"`
	InkType     *string        `json:"ink_type"`
	TipSize     *string        `json:"tip_size"`
	Color       *string        `json:"color"`
	MinPrice    pgtype.Numeric `json:"min_price"`
	MaxPrice    pgtype.Numeric `json:"max_price"`
	MinWeight   pgtype.Numeric `json:"min_weight"`
	MaxWeight   pgtype.Numeric `json:"max_weight"`
	MinRating   *float64       `json:"min_rating"`
	Purpose     *string        `json:"purpose"`
	OffsetCount int32          `json:"offset_count"`
	LimitCount  int32          `json:"limit_count"`
}

type ListPensRow struct {
	ID              uuid.UUID          `json:"id"`
	BrandID         uuid.UUID          `json:"brand_id"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	Description     string             `json:"description"`
	Type            string             `json:"type"`
	InkType         string             `json:"ink_type"`
	TipSize         string             `json:"tip_size"`
	Price           float64            `json:"price"`
	Weight          float64            `json:"weight"`
	Length          pgtype.Numeric     `json:"length"`
	GripMaterial    *string            `json:"grip_material"`
	BodyMaterial    *string            `json:"body_material"`
	Color           *string            `json:"color"`
	SmoothnessScore float64            `json:"smoothness_score"`
	ComfortScore    float64            `json:"comfort_score"`
	DurabilityScore float64            `json:"durability_score"`
	PrecisionScore  float64            `json:"precision_score"`
	DesignScore     float64            `json:"design_score"`
	GripScore       float64            `json:"grip_score"`
	InkQuality      float64            `json:"ink_quality"`
	ImageUrl        *string            `json:"image_url"`
	WhyGood         *string            `json:"why_good"`
	SuitableFor     *string            `json:"suitable_for"`
	NotSuitableFor  *string            `json:"not_suitable_for"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	BrandName       string             `json:"brand_name"`
	BrandSlug       string             `json:"brand_slug"`
	AvgRating       float64            `json:"avg_rating"`
	ReviewCount     int32              `json:"review_count"`
}

func (q *Queries) ListPens(ctx context.Context, arg ListPensParams) ([]ListPensRow, error) {
	rows, err := q.db.Query(ctx, listPens,
		arg.BrandSlug,
		arg.Type,
		arg.InkType,
		arg.TipSize,
		arg.Color,
		arg.MinPrice,
		arg.MaxPrice,
		arg.MinWeight,
		arg.MaxWeight,
		arg.MinRating,
		arg.Purpose,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPensRow
	for rows.Next() {
		var i ListPensRow
		if err := rows.Scan(
			&i.ID,
			&i.BrandID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Type,
			&i.InkType,
			&i.TipSize,
			&i.Price,
			&i.Weight,
			&i.Length,
			&i.GripMaterial,
			&i.BodyMaterial,
			&i.Color,
			&i.SmoothnessScore,
			&i.ComfortScore,
			&i.DurabilityScore,
			&i.PrecisionScore,
			&i.DesignScore,
			&i.GripScore,
			&i.InkQuality,
			&i.ImageUrl,
			&i.WhyGood,
			&i.SuitableFor,
			&i.NotSuitableFor,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BrandName,
			&i.BrandSlug,
			&i.AvgRating,
			&i.ReviewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPensByIDs = `-- name: ListPensByIDs :many
SELECT
    p.id, p.brand_id, p.name, p.slug, p.description, p.type, p.ink_type, p.tip_size, p.price, p.weight, p.length, p.grip_material, p.body_material, p.color, p.smoothness_score, p.comfort_score, p.durability_score, p.precision_score, p.design_score, p.grip_score, p.ink_quality, p.image_url, p.why_good, p.suitable_for, p.not_suitable_for, p.created_at, p.updated_at,
    b.name AS brand_name,
    b.slug AS brand_slug,
    COALESCE(AVG(r.rating), 0)::float AS avg_rating,
    COUNT(r.id)::int AS review_count
FROM pens p
JOIN brands b ON b.id = p.brand_id
LEFT JOIN reviews r ON r.pen_id = p.id
WHERE p.id = ANY($1::uuid[])
GROUP BY p.id, b.name, b.slug
`

type ListPensByIDsRow struct {
	ID              uuid.UUID          `json:"id"`
	BrandID         uuid.UUID          `json:"brand_id"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	Description     string             `json:"description"`
	Type            string             `json:"type"`
	InkType         string             `json:"ink_type"`
	TipSize         string             `json:"tip_size"`
	Price           float64            `json:"price"`
	Weight          float64            `json:"weight"`
	Length          pgtype.Numeric     `json:"length"`
	GripMaterial    *string            `json:"grip_material"`
	BodyMaterial    *string            `json:"body_material"`
	Color           *string            `json:"color"`
	SmoothnessScore float64            `json:"smoothness_score"`
	ComfortScore    float64            `json:"comfort_score"`
	DurabilityScore float64            `json:"durability_score"`
	PrecisionScore  float64            `json:"precision_score"`
	DesignScore     float64            `json:"design_score"`
	GripScore       float64            `json:"grip_score"`
	InkQuality      float64            `json:"ink_quality"`
	ImageUrl        *string            `json:"image_url"`
	WhyGood         *string            `json:"why_good"`
	SuitableFor     *string            `json:"suitable_for"`
	NotSuitableFor  *string            `json:"not_suitable_for"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	BrandName       string             `json:"brand_name"`
	BrandSlug       string             `json:"brand_slug"`
	AvgRating       float64            `json:"avg_rating"`
	ReviewCount     int32              `json:"review_count"`
}

func (q *Queries) ListPensByIDs(ctx context.Context, ids []uuid.UUID) ([]ListPensByIDsRow, error) {
	rows, err := q.db.Query(ctx, listPensByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPensByIDsRow
	for rows.Next() {
		var i ListPensByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.BrandID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Type,
			&i.InkType,
			&i.TipSize,
			&i.Price,
			&i.Weight,
			&i.Length,
			&i.GripMaterial,
			&i.BodyMaterial,
			&i.Color,
			&i.SmoothnessScore,
			&i.ComfortScore,
			&i.DurabilityScore,
			&i.PrecisionScore,
			&i.DesignScore,
			&i.GripScore,
			&i.InkQuality,
			&i.ImageUrl,
			&i.WhyGood,
			&i.SuitableFor,
			&i.NotSuitableFor,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BrandName,
			&i.BrandSlug,
			&i.AvgRating,
			&i.ReviewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPensBySlugs = `-- name: ListPensBySlugs :many
SELECT
    p.id, p.brand_id, p.name, p.slug, p.description, p.type, p.ink_type, p.tip_size, p.price, p.weight, p.length, p.grip_material, p.body_material, p.color, p.smoothness_score, p.comfort_score, p.durability_score, p.precision_score, p.design_score, p.grip_score, p.ink_quality, p.image_url, p.why_good, p.suitable_for, p.not_suitable_for, p.created_at, p.updated_at,
    b.name AS brand_name,
    b.slug AS brand_slug,
    COALESCE(AVG(r.rating), 0)::float AS avg_rating,
    COUNT(r.id)::int AS review_count
FROM pens p
JOIN brands b ON b.id = p.brand_id
LEFT JOIN reviews r ON r.pen_id = p.id
WHERE p.slug = ANY($1::text[])
GROUP BY p.id, b.name, b.slug
`

type ListPensBySlugsRow struct {
	ID              uuid.UUID          `json:"id"`
	BrandID         uuid.UUID          `json:"brand_id"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	Description     string             `json:"description"`
	Type            string             `json:"type"`
	InkType         string             `json:"ink_type"`
	TipSize         string             `json:"tip_size"`
	Price           float64            `json:"price"`
	Weight          float64            `json:"weight"`
	Length          pgtype.Numeric     `json:"length"`
	GripMaterial    *string            `json:"grip_material"`
	BodyMaterial    *string            `json:"body_material"`
	Color           *string            `json:"color"`
	SmoothnessScore float64            `json:"smoothness_score"`
	ComfortScore    float64            `json:"comfort_score"`
	DurabilityScore float64            `json:"durability_score"`
	PrecisionScore  float64            `json:"precision_score"`
	DesignScore     float64            `json:"design_score"`
	GripScore       float64            `json:"grip_score"`
	InkQuality      float64            `json:"ink_quality"`
	ImageUrl        *string            `json:"image_url"`
	WhyGood         *string            `json:"why_good"`
	SuitableFor     *string            `json:"suitable_for"`
	NotSuitableFor  *string            `json:"not_suitable_for"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	BrandName       string             `json:"brand_name"`
	BrandSlug       string             `json:"brand_slug"`
	AvgRating       float64            `json:"avg_rating"`
	ReviewCount     int32              `json:"review_count"`
}

func (q *Queries) ListPensBySlugs(ctx context.Context, slugs []string) ([]ListPensBySlugsRow, error) {
	rows, err := q.db.Query(ctx, listPensBySlugs, slugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPensBySlugsRow
	for rows.Next() {
		var i ListPensBySlugsRow
		if err := rows.Scan(
			&i.ID,
			&i.BrandID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Type,
			&i.InkType,
			&i.TipSize,
			&i.Price,
			&i.Weight,
			&i.Length,
			&i.GripMaterial,
			&i.BodyMaterial,
			&i.Color,
			&i.SmoothnessScore,
			&i.ComfortScore,
			&i.DurabilityScore,
			&i.PrecisionScore,
			&i.DesignScore,
			&i.GripScore,
			&i.InkQuality,
			&i.ImageUrl,
			&i.WhyGood,
			&i.SuitableFor,
			&i.NotSuitableFor,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BrandName,
			&i.BrandSlug,
			&i.AvgRating,
			&i.ReviewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPopularPens = `-- name: ListPopularPens :many
SELECT
    p.id, p.brand_id, p.name, p.slug, p.description, p.type, p.ink_type, p.tip_size, p.price, p.weight, p.length, p.grip_material, p.body_material, p.color, p.smoothness_score, p.comfort_score, p.durability_score, p.precision_score, p.design_score, p.grip_score, p.ink_quality, p.image_url, p.why_good, p.suitable_for, p.not_suitable_for, p.created_at, p.updated_at,
    b.name AS brand_name,
    b.slug AS brand_slug,
    COALESCE(AVG(r.rating), 0)::float AS avg_rating,
    COUNT(r.id)::int AS review_count
FROM pens p
JOIN brands b ON b.id = p.brand_id
LEFT JOIN reviews r ON r.pen_id = p.id
GROUP BY p.id, b.name, b.slug
ORDER BY avg_rating DESC, review_count DESC
LIMIT $1
`

type ListPopularPensRow struct {
	ID              uuid.UUID          `json:"id"`
	BrandID         uuid.UUID          `json:"brand_id"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	Description     string             `json:"description"`
	Type            string             `json:"type"`
	InkType         string             `json:"ink_type"`
	TipSize         string             `json:"tip_size"`
	Price           float64            `json:"price"`
	Weight          float64            `json:"weight"`
	Length          pgtype.Numeric     `json:"length"`
	GripMaterial    *string            `json:"grip_material"`
	BodyMaterial    *string            `json:"body_material"`
	Color           *string            `json:"color"`
	SmoothnessScore float64            `json:"smoothness_score"`
	ComfortScore    float64            `json:"comfort_score"`
	DurabilityScore float64            `json:"durability_score"`
	PrecisionScore  float64            `json:"precision_score"`
	DesignScore     float64            `json:"design_score"`
	GripScore       float64            `json:"grip_score"`
	InkQuality      float64            `json:"ink_quality"`
	ImageUrl        *string            `json:"image_url"`
	WhyGood         *string            `json:"why_good"`
	SuitableFor     *string            `json:"suitable_for"`
	NotSuitableFor  *string            `json:"not_suitable_for"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	BrandName       string             `json:"brand_name"`
	BrandSlug       string             `json:"brand_slug"`
	AvgRating       float64            `json:"avg_rating"`
	ReviewCount     int32              `json:"review_count"`
}

func (q *Queries) ListPopularPens(ctx context.Context, limit int32) ([]ListPopularPensRow, error) {
	rows, err := q.db.Query(ctx, listPopularPens, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPopularPensRow
	for rows.Next() {
		var i ListPopularPensRow
		if err := rows.Scan(
			&i.ID,
			&i.BrandID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Type,
			&i.InkType,
			&i.TipSize,
			&i.Price,
			&i.Weight,
			&i.Length,
			&i.GripMaterial,
			&i.BodyMaterial,
			&i.Color,
			&i.SmoothnessScore,
			&i.ComfortScore,
			&i.DurabilityScore,
			&i.PrecisionScore,
			&i.DesignScore,
			&i.GripScore,
			&i.InkQuality,
			&i.ImageUrl,
			&i.WhyGood,
			&i.SuitableFor,
			&i.NotSuitableFor,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BrandName,
			&i.BrandSlug,
			&i.AvgRating,
			&i.ReviewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, name, slug FROM tags ORDER BY name
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPens = `-- name: SearchPens :many
SELECT
    p.id, p.brand_id, p.name, p.slug, p.description, p.type, p.ink_type, p.tip_size, p.price, p.weight, p.length, p.grip_material, p.body_material, p.color, p.smoothness_score, p.comfort_score, p.durability_score, p.precision_score, p.design_score, p.grip_score, p.ink_quality, p.image_url, p.why_good, p.suitable_for, p.not_suitable_for, p.created_at, p.updated_at,
    b.name AS brand_name,
    b.slug AS brand_slug,
    COALESCE(AVG(r.rating), 0)::float AS avg_rating,
    COUNT(r.id)::int AS review_count
FROM pens p
JOIN brands b ON b.id = p.brand_id
LEFT JOIN reviews r ON r.pen_id = p.id
WHERE p.name ILIKE '%' || $1 || '%'
   OR b.name ILIKE '%' || $1 || '%'
   OR p.slug ILIKE '%' || $1 || '%'
GROUP BY p.id, b.name, b.slug
ORDER BY GREATEST(similarity(p.name, $1), similarity(b.name, $1)) DESC
LIMIT 12
`

type SearchPensRow struct {
	ID              uuid.UUID          `json:"id"`
	BrandID         uuid.UUID          `json:"brand_id"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	Description     string             `json:"description"`
	Type            string             `json:"type"`
	InkType         string             `json:"ink_type"`
	TipSize         string             `json:"tip_size"`
	Price           float64            `json:"price"`
	Weight          float64            `json:"weight"`
	Length          pgtype.Numeric     `json:"length"`
	GripMaterial    *string            `json:"grip_material"`
	BodyMaterial    *string            `json:"body_material"`
	Color           *string            `json:"color"`
	SmoothnessScore float64            `json:"smoothness_score"`
	ComfortScore    float64            `json:"comfort_score"`
	DurabilityScore float64            `json:"durability_score"`
	PrecisionScore  float64            `json:"precision_score"`
	DesignScore     float64            `json:"design_score"`
	GripScore       float64            `json:"grip_score"`
	InkQuality      float64            `json:"ink_quality"`
	ImageUrl        *string            `json:"image_url"`
	WhyGood         *string            `json:"why_good"`
	SuitableFor     *string            `json:"suitable_for"`
	NotSuitableFor  *string            `json:"not_suitable_for"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	BrandName       string             `json:"brand_name"`
	BrandSlug       string             `json:"brand_slug"`
	AvgRating       float64            `json:"avg_rating"`
	ReviewCount     int32              `json:"review_count"`
}

func (q *Queries) SearchPens(ctx context.Context, query *string) ([]SearchPensRow, error) {
	rows, err := q.db.Query(ctx, searchPens, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPensRow
	for rows.Next() {
		var i SearchPensRow
		if err := rows.Scan(
			&i.ID,
			&i.BrandID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Type,
			&i.InkType,
			&i.TipSize,
			&i.Price,
			&i.Weight,
			&i.Length,
			&i.GripMaterial,
			&i.BodyMaterial,
			&i.Color,
			&i.SmoothnessScore,
			&i.ComfortScore,
			&i.DurabilityScore,
			&i.PrecisionScore,
			&i.DesignScore,
			&i.GripScore,
			&i.InkQuality,
			&i.ImageUrl,
			&i.WhyGood,
			&i.SuitableFor,
			&i.NotSuitableFor,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BrandName,
			&i.BrandSlug,
			&i.AvgRating,
			&i.ReviewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
