// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (user_id, pen_id, rating, title, body)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, pen_id, rating, title, body, created_at
`

type CreateReviewParams struct {
	UserID uuid.UUID `json:"user_id"`
	PenID  uuid.UUID `json:"pen_id"`
	Rating int16     `json:"rating"`
	Title  *string   `json:"title"`
	Body   string    `json:"body"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.UserID,
		arg.PenID,
		arg.Rating,
		arg.Title,
		arg.Body,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PenID,
		&i.Rating,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const getReviewByUserAndPen = `-- name: GetReviewByUserAndPen :one
SELECT id, user_id, pen_id, rating, title, body, created_at FROM reviews WHERE user_id = $1 AND pen_id = $2
`

type GetReviewByUserAndPenParams struct {
	UserID uuid.UUID `json:"user_id"`
	PenID  uuid.UUID `json:"pen_id"`
}

func (q *Queries) GetReviewByUserAndPen(ctx context.Context, arg GetReviewByUserAndPenParams) (Review, error) {
	row := q.db.QueryRow(ctx, getReviewByUserAndPen, arg.UserID, arg.PenID)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PenID,
		&i.Rating,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const listRecentReviews = `-- name: ListRecentReviews :many
SELECT r.id, r.user_id, r.pen_id, r.rating, r.title, r.body, r.created_at, u.name AS user_name, p.name AS pen_name, p.slug AS pen_slug, b.name AS brand_name
FROM reviews r
JOIN users u ON u.id = r.user_id
JOIN pens p ON p.id = r.pen_id
JOIN brands b ON b.id = p.brand_id
ORDER BY r.created_at DESC
LIMIT $1
`

type ListRecentReviewsRow struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	PenID     uuid.UUID          `json:"pen_id"`
	Rating    int16              `json:"rating"`
	Title     *string            `json:"title"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UserName  string             `json:"user_name"`
	PenName   string             `json:"pen_name"`
	PenSlug   string             `json:"pen_slug"`
	BrandName string             `json:"brand_name"`
}

func (q *Queries) ListRecentReviews(ctx context.Context, limit int32) ([]ListRecentReviewsRow, error) {
	rows, err := q.db.Query(ctx, listRecentReviews, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentReviewsRow
	for rows.Next() {
		var i ListRecentReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PenID,
			&i.Rating,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.UserName,
			&i.PenName,
			&i.PenSlug,
			&i.BrandName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByPen = `-- name: ListReviewsByPen :many
SELECT r.id, r.user_id, r.pen_id, r.rating, r.title, r.body, r.created_at, u.name AS user_name
FROM reviews r
JOIN users u ON u.id = r.user_id
WHERE r.pen_id = $1
ORDER BY r.created_at DESC
`

type ListReviewsByPenRow struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	PenID     uuid.UUID          `json:"pen_id"`
	Rating    int16              `json:"rating"`
	Title     *string            `json:"title"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UserName  string             `json:"user_name"`
}

func (q *Queries) ListReviewsByPen(ctx context.Context, penID uuid.UUID) ([]ListReviewsByPenRow, error) {
	rows, err := q.db.Query(ctx, listReviewsByPen, penID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewsByPenRow
	for rows.Next() {
		var i ListReviewsByPenRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PenID,
			&i.Rating,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
