// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seed.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const attachPenCategory = `-- name: AttachPenCategory :exec
INSERT INTO pen_categories (pen_id, category_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AttachPenCategoryParams struct {
	PenID      uuid.UUID `json:"pen_id"`
	CategoryID uuid.UUID `json:"category_id"`
}

func (q *Queries) AttachPenCategory(ctx context.Context, arg AttachPenCategoryParams) error {
	_, err := q.db.Exec(ctx, attachPenCategory, arg.PenID, arg.CategoryID)
	return err
}

const attachPenTag = `-- name: AttachPenTag :exec
INSERT INTO pen_tags (pen_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AttachPenTagParams struct {
	PenID uuid.UUID `json:"pen_id"`
	TagID uuid.UUID `json:"tag_id"`
}

func (q *Queries) AttachPenTag(ctx context.Context, arg AttachPenTagParams) error {
	_, err := q.db.Exec(ctx, attachPenTag, arg.PenID, arg.TagID)
	return err
}

const insertBrand = `-- name: InsertBrand :one
INSERT INTO brands (name, slug, description)
VALUES ($1, $2, $3)
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description
RETURNING id, name, slug, logo_url, description, created_at
`

type InsertBrandParams struct {
	Name        string  `json:"name"`
	Slug        string  `json:"slug"`
	Description *string `json:"description"`
}

func (q *Queries) InsertBrand(ctx context.Context, arg InsertBrandParams) (Brand, error) {
	row := q.db.QueryRow(ctx, insertBrand, arg.Name, arg.Slug, arg.Description)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LogoUrl,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const insertCategory = `-- name: InsertCategory :one
INSERT INTO categories (name, slug)
VALUES ($1, $2)
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name, slug
`

type InsertCategoryParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) InsertCategory(ctx context.Context, arg InsertCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, insertCategory, arg.Name, arg.Slug)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.Slug)
	return i, err
}

const insertFeature = `-- name: InsertFeature :one
INSERT INTO pen_features (key, label)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label
RETURNING id, key, label
`

type InsertFeatureParams struct {
	Key   string `json:"key"`
	Label string `json:"label"`
}

func (q *Queries) InsertFeature(ctx context.Context, arg InsertFeatureParams) (PenFeature, error) {
	row := q.db.QueryRow(ctx, insertFeature, arg.Key, arg.Label)
	var i PenFeature
	err := row.Scan(&i.ID, &i.Key, &i.Label)
	return i, err
}

const insertPen = `-- name: InsertPen :one
INSERT INTO pens (
    brand_id, name, slug, description, type, ink_type, tip_size, price, weight, length,
    grip_material, body_material, color, smoothness_score, comfort_score, durability_score,
    precision_score, design_score, grip_score, ink_quality, image_url, why_good, suitable_for, not_suitable_for
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16,
    $17, $18, $19, $20, $21, $22, $23, $24
)
ON CONFLICT (slug) DO UPDATE SET
    description = EXCLUDED.description,
    type = EXCLUDED.type,
    ink_type = EXCLUDED.ink_type,
    tip_size = EXCLUDED.tip_size,
    price = EXCLUDED.price,
    weight = EXCLUDED.weight,
    length = EXCLUDED.length,
    grip_material = EXCLUDED.grip_material,
    body_material = EXCLUDED.body_material,
    color = EXCLUDED.color,
    smoothness_score = EXCLUDED.smoothness_score,
    comfort_score = EXCLUDED.comfort_score,
    durability_score = EXCLUDED.durability_score,
    precision_score = EXCLUDED.precision_score,
    design_score = EXCLUDED.design_score,
    grip_score = EXCLUDED.grip_score,
    ink_quality = EXCLUDED.ink_quality,
    image_url = EXCLUDED.image_url,
    why_good = EXCLUDED.why_good,
    suitable_for = EXCLUDED.suitable_for,
    not_suitable_for = EXCLUDED.not_suitable_for,
    updated_at = NOW()
RETURNING id, brand_id, name, slug, description, type, ink_type, tip_size, price, weight, length, grip_material, body_material, color, smoothness_score, comfort_score, durability_score, precision_score, design_score, grip_score, ink_quality, image_url, why_good, suitable_for, not_suitable_for, created_at, updated_at
`

type InsertPenParams struct {
	BrandID         uuid.UUID      `json:"brand_id"`
	Name            string         `json:"name"`
	Slug            string         `json:"slug"`
	Description     string         `json:"description"`
	Type            string         `json:"type"`
	InkType         string         `json:"ink_type"`
	TipSize         string         `json:"tip_size"`
	Price           float64        `json:"price"`
	Weight          float64        `json:"weight"`
	Length          pgtype.Numeric `json:"length"`
	GripMaterial    *string        `json:"grip_material"`
	BodyMaterial    *string        `json:"body_material"`
	Color           *string        `json:"color"`
	SmoothnessScore float64        `json:"smoothness_score"`
	ComfortScore    float64        `json:"comfort_score"`
	DurabilityScore float64        `json:"durability_score"`
	PrecisionScore  float64        `json:"precision_score"`
	DesignScore     float64        `json:"design_score"`
	GripScore       float64        `json:"grip_score"`
	InkQuality      float64        `json:"ink_quality"`
	ImageUrl        *string        `json:"image_url"`
	WhyGood         *string        `json:"why_good"`
	SuitableFor     *string        `json:"suitable_for"`
	NotSuitableFor  *string        `json:"not_suitable_for"`
}

func (q *Queries) InsertPen(ctx context.Context, arg InsertPenParams) (Pen, error) {
	row := q.db.QueryRow(ctx, insertPen,
		arg.BrandID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Type,
		arg.InkType,
		arg.TipSize,
		arg.Price,
		arg.Weight,
		arg.Length,
		arg.GripMaterial,
		arg.BodyMaterial,
		arg.Color,
		arg.SmoothnessScore,
		arg.ComfortScore,
		arg.DurabilityScore,
		arg.PrecisionScore,
		arg.DesignScore,
		arg.GripScore,
		arg.InkQuality,
		arg.ImageUrl,
		arg.WhyGood,
		arg.SuitableFor,
		arg.NotSuitableFor,
	)
	var i Pen
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Type,
		&i.InkType,
		&i.TipSize,
		&i.Price,
		&i.Weight,
		&i.Length,
		&i.GripMaterial,
		&i.BodyMaterial,
		&i.Color,
		&i.SmoothnessScore,
		&i.ComfortScore,
		&i.DurabilityScore,
		&i.PrecisionScore,
		&i.DesignScore,
		&i.GripScore,
		&i.InkQuality,
		&i.ImageUrl,
		&i.WhyGood,
		&i.SuitableFor,
		&i.NotSuitableFor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertReviewIfMissing = `-- name: InsertReviewIfMissing :exec
INSERT INTO reviews (user_id, pen_id, rating, title, body)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, pen_id) DO NOTHING
`

type InsertReviewIfMissingParams struct {
	UserID uuid.UUID `json:"user_id"`
	PenID  uuid.UUID `json:"pen_id"`
	Rating int16     `json:"rating"`
	Title  *string   `json:"title"`
	Body   string    `json:"body"`
}

func (q *Queries) InsertReviewIfMissing(ctx context.Context, arg InsertReviewIfMissingParams) error {
	_, err := q.db.Exec(ctx, insertReviewIfMissing,
		arg.UserID,
		arg.PenID,
		arg.Rating,
		arg.Title,
		arg.Body,
	)
	return err
}

const insertTag = `-- name: InsertTag :one
INSERT INTO tags (name, slug)
VALUES ($1, $2)
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name, slug
`

type InsertTagParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) InsertTag(ctx context.Context, arg InsertTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, insertTag, arg.Name, arg.Slug)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.Slug)
	return i, err
}

const insertUserIfMissing = `-- name: InsertUserIfMissing :one
INSERT INTO users (email, password_hash, name, role)
VALUES ($1, $2, $3, $4)
ON CONFLICT (email) DO UPDATE SET name = EXCLUDED.name, role = EXCLUDED.role
RETURNING id, email, password_hash, name, role, created_at, updated_at
`

type InsertUserIfMissingParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Name         string `json:"name"`
	Role         string `json:"role"`
}

func (q *Queries) InsertUserIfMissing(ctx context.Context, arg InsertUserIfMissingParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUserIfMissing,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertFeatureValue = `-- name: UpsertFeatureValue :exec
INSERT INTO pen_feature_values (pen_id, feature_id, value)
VALUES ($1, $2, $3)
ON CONFLICT (pen_id, feature_id) DO UPDATE SET value = EXCLUDED.value
`

type UpsertFeatureValueParams struct {
	PenID     uuid.UUID `json:"pen_id"`
	FeatureID uuid.UUID `json:"feature_id"`
	Value     string    `json:"value"`
}

func (q *Queries) UpsertFeatureValue(ctx context.Context, arg UpsertFeatureValueParams) error {
	_, err := q.db.Exec(ctx, upsertFeatureValue, arg.PenID, arg.FeatureID, arg.Value)
	return err
}
